[package]
name = "carbonaria"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = { version = "0.7.0", features = ["dynamic"] }
bevy = "0.7.0"
derive-error = "0.0.5"

