[package]
name = "carbonaria"
version = "1.0.0"
edition = "2021"
default-run = "main"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Swap these for production builds:
# bevy = { version = "0.14", features = ["dynamic"] }
bevy = { version = "0.14" }
derive-error = "0.0.5"
bevy_rapier2d = "0.27"
rand = { version = "0.8.5", features = ["small_rng"] }
bevy-inspector-egui = "0.25"
clap = { version = "4.5", features = ["derive"] }


[[bin]]
name = "main"
path = "src/main.rs"


